### ISSUE TITLE
References to vars that don't exist

### ISSUE THREAD

**Issue by djahren** [shish/link#11]
In the current version of the code on github there are a few references to vars that don't exist.
**link.py**
`Line 554 and 559: for q in pets.questions:`
questions is not defined, it appears it was changed to contents on line 541

**models.py**
`Line 55: secondary=Friendship.__table__,`
Should be: `secondary=Friendship.__tablename__,`

In the Survey class there is references to self.questions on lines 126,129,134, and 137

In the Response class there's reference to self.answers on line 215

**Comment by shish** [comment]
These are created at runtime by python magic (sqlalchemy specifically) - eg

```
class Question(Base):
    survey = relationship("Survey", backref=backref("questions"))
```

as well as creating a link in one direction (`question.survey`), the `backref` creates an array of links in the other direction (`survey.questions`)

I have a vague feeling that at some point in the past it was necessary to define relationships this way (`x -> y` and `y -> x` in the same place); I wonder if it's now possible to define them in the more natural way where each class defines its own relationships...

`__table__` is similar magic, IIRC - it's not written in the code anywhere, but the database library will create it after it starts running

**Comment by shish** [comment]
Looks like it is now possible to define relationships on both sides \o/

https://docs.sqlalchemy.org/en/13/orm/basic_relationships.html#one-to-many

**Comment by shish** [comment]
Updated the code to define relationships from both ends (and also added a bunch of unit tests, though nowhere near full coverage yet)
